README.md, SAMLTeamSyncAD.py, settings.yml.sample
This pull request addresses the following:
- #15 Sample config missing keys/values
- #16 UnicodeDecodeError
- #14 Searching LDAP by dn not working
- Deprecates Python 2.x support
=> Deprecated Python 2.x, fix bugs

SAMLTeamSyncAD.py
=> fixed the store-const error

README.md, SAMLTeamSyncAD.py, settings.yml.sample
Addresses #20
```
GITHUB_TOKEN=
AD_BIND_PASSWORD=
```
=> Added support for environment secrets

Dockerfile
=> Update Dockerfile to Python 3.x

.env.example, Pipfile, Pipfile.lock, app.py, githubapp/core.py
Adding a sample scheduling library.  Don't know at the moment how to translate a cron syntax to the scheduling decorator, I will look at that next.
=> Adding the scheduler sample

.env.example, README.md, app.py, githubapp/__init__.py
Adds the ability to set cron style scheduling for the background job.
=> Adding cron style scheduling

README.md, app.py, githubapp/__init__.py, syncmap.yml.example
This adds custom mapping, for #4
=> added custom group mapping

githubapp/__init__.py
This fixes the issue logged in #44
=> Fixing #44

Dockerfile
=> fixing broken pipenv install

.github/CONTRIBUTING.md, README.md
This PR will address the following:
- `CONTRIBUTING.md`
- `CODE_OF_CONDUCT.md`
- ~`DeployToDocker.md`~
=> Adding OSS Info

app.py, githubapp/azuread.py
This PR fixes the issue where installing the app in multiple orgs breaks the sync. 
Closes #68
=> Fix multi-installation bug

app.py
add_or_update_membership is adding user to org, but is expacting always
200 - catch 404 response, when user not login
=> Add user to organization if found

app.py, githubapp/azuread.py
Connection is pushed, but never poped from stack
=> Close connections opened on cron sync

README.md, syncmap.yml.example
=> Update sample custom map

.env.example.aad, .env.example.ldap, .env.example.okta, .env.example.onelogin, README.md
=> Adding ADD_MEMBER and LDAP_SYNC_ATTRIBUTE to the readme

README.md, app.py, githubapp/__init__.py
Add option for syncing only teams defined in syncmap.
=> optional syncmap only

README.md
@stacycarter - would something like this work? If there's better language around this feel free to suggest it here 👍 .
=> Add clarifying support language

githubapp/okta.py
=> Custom attribute not used #85

githubapp/core.py
This removes the webhook verification bypass
=> Remove webhook verification bypass

.github/workflows/docker-publish.yml
=> Add publishing of a docker image

.env.example.aad, .env.example.ldap, .env.example.okta, .env.example.onelogin, README.md, app.py, githubapp/__init__.py
=> Remove org members without team

README.md
Just a small change noticed while reading documentation :)
=> docs: README.md typos

README.md, app.py, syncmap.yml.example
=> Add the possibility of adding organizations to the syncmap file

README.md
=> Update Pipfile requirements in the README

Pipfile, Pipfile.lock, app.py
=> #161 disable prereleases in Pipfile

.env.example.okta, README.md, githubapp/azuread.py, githubapp/ldap.py, githubapp/okta.py, githubapp/onelogin.py
If the variable EMU_SHORTCODE is set, then the shortcode is appended to the username found in okta
=> Support emu accounts by adding EMU_SHORTCODE env var

README.md, app.py
=> comment out FLASK_APP env var to run once as a script

Pipfile, Pipfile.lock, app.py, githubapp/ldap.py
This fixes the build due to broken dependencies
fixes #172
=> Fix broken dependencies

Pipfile, Pipfile.lock, README.md, githubapp/__init__.py, githubapp/googleworkspace.py, githubapp/ldap.py
Co-Authored-By: Dmitry Chepurovskiy
This addresses the merge conflicts in #155 
@dm3ch this should be good to go with the recent updates in dependencies
closes #155 
closes #151
=> added support for Google Workspaces

app.py, githubapp/ldap.py, syncmap.yml.example
This adds the ability to filter the sync based on group prefixes
closes #142
=> Add ability to filter based on group prefixes

githubapp/core.py
Some deployment systems require a health check
=> Add a health check endpoint
